### ISSUE TITLE
packet.toBuffer() undefined is not a function

### ISSUE THREAD

**Issue by siboulet** [kmpm/node-mdns-js#24]
I can't get example/services.js to work on node v0.11.14.

$ node examples/service.js 
xxx/node_modules/mdns-js/lib/advertisement.js:15
  var buf = packet.toBuffer();
                   ^
TypeError: undefined is not a function
    at Object.internal.sendDNSPacket (xxx/node_modules/mdns-js/lib/advertisement.js:15:20)
    at internal.probeAndAdvertise (xxx/node_modules/mdns-js/lib/advertisement.js:196:16)
    at Advertisement.start (xxx/node_modules/mdns-js/lib/advertisement.js:258:30)
    at Object.<anonymous> (xxx/node_modules/mdns-js/examples/service.js:10:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:124:16)

**Comment by kmpm** [comment]
I don't get it under v0.12 but a lot of other things have happened in the meantime.
I will close this issue in a couple of days if I don't see it again or get more feedback.
Thanks.

**Comment by siboulet** [comment]
@kmpm I'm no longer using this module so can't confirm. Thanks for looking into it.
